### PR TITLE
Update to 2.4.59 for security issues, bugs and improvements

### PR DESCRIPTION
**Pull request by reporter4u**
Hi,

a new Httpd version has been released with some CVE fix, bugs fix and improvements.

I hope you can validate it and do reviews.

Thank you.

Roberto

### CODE REVIEW

**Comment by fraenki** [comment]
@jeffsheltren Requesting a review :blush:

**Comment by reporter4u** [comment]
Is there someone available to review and release the test packages?

Tnks!

**Comment by reporter4u** [comment]
> @jeffsheltren Requesting a review 😊

@carlwgeorge can you help us, please?

**Comment by fraenki** [comment]
ping @jeffsheltren @carlwgeorge :relaxed:

**Comment by claudeseedbox** [comment]
Do you guys think there's any chance we get that updated or IUS will stop maintaining since C7 is going EOL in 25 days?

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more issues or pull requests.

ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

iusrepo/announce#41

**Pull request closed without merging**
